// Kazakh localization for Judo-Arena
export const kz = {
  // App
  appName: 'Judo-Arena',
  tagline: 'Дзюдо турнирлерін басқарудың премиум платформасы',

  // Navigation
  nav: {
    home: 'Басты бет',
    dashboard: 'Басқару тақтасы',
    tournaments: 'Турнирлер',
    athletes: 'Спортшылар',
    applications: 'Өтінімдер',
    brackets: 'Турнир торы',
    users: 'Пайдаланушылар',
    clubs: 'Клубтар',
    profile: 'Профиль',
    results: 'Нәтижелер',
    participation: 'Қатысу',
    tatamiQueue: 'Татами кезегі',
    matchControl: 'Жекпе-жек басқару',
    scoreboard: 'Табло',
    login: 'Кіру',
    register: 'Тіркелу',
    logout: 'Шығу',
    settings: 'Баптаулар',
  },

  // Roles
  roles: {
    athlete: 'Спортшы',
    coach: 'Жаттықтырушы',
    admin: 'Әкімші',
    judge: 'Төреші',
    switchRole: 'Рөлді ауыстыру',
    demoMode: 'Демо режимі',
  },

  // Statuses
  status: {
    upcoming: 'Алдағы',
    active: 'Белсенді',
    completed: 'Аяқталған',
    draft: 'Жоба',
    pending: 'Күтілуде',
    approved: 'Мақұлданған',
    rejected: 'Қабылданбаған',
    scheduled: 'Жоспарланған',
    inProgress: 'Жүріп жатыр',
    live: 'Тікелей',
    blocked: 'Бұғатталған',
  },

  // Home page
  home: {
    heroTitle: 'Дзюдо турнирлерін басқарудың заманауи платформасы',
    heroSubtitle: 'Турнирлерді ұйымдастыру, спортшыларды тіркеу, жекпе-жектерді басқару және нәтижелерді бақылау — барлығы бір жерде',
    heroCta: 'Бастау',
    heroSecondary: 'Толығырақ',
    features: 'Мүмкіндіктер',
    featureTournament: 'Турнир басқару',
    featureTournamentDesc: 'Турнирлерді құру, санаттарды баптау, өтінімдерді қабылдау және жүргізу кестесін автоматты түрде құру',
    featureBracket: 'Турнир торы',
    featureBracketDesc: 'Интерактивті турнир торлары, нақты уақыттағы жаңартулар және кәсіби визуализация',
    featureJudge: 'Төреші панелі',
    featureJudgeDesc: 'Жекпе-жекті толық басқару: таймер, ұпайлар, жазалар және UKO жүйесі',
    featureAnalytics: 'Аналитика',
    featureAnalyticsDesc: 'Толық статистика, спортшылар рейтингі және турнир нәтижелерінің талдауы',
    rolesTitle: 'Әр рөлге арналған',
    roleAthleteDesc: 'Турнирлерге тіркелу, нәтижелерді көру, өз статистикасын бақылау',
    roleCoachDesc: 'Спортшыларды басқару, өтінімдер жіберу, клуб нәтижелерін талдау',
    roleAdminDesc: 'Турнирлерді ұйымдастыру, өтінімдерді тексеру, жүйені басқару',
    roleJudgeDesc: 'Жекпе-жектерді басқару, ұпайларды белгілеу, нәтижелерді растау',
    liveTournament: 'Тікелей турнир',
    previewTitle: 'Платформаны танысу',
    ctaTitle: 'Дзюдо турнирлеріңізді жаңа деңгейге көтеріңіз',
    ctaButton: 'Тегін бастау',
    stats: {
      tournaments: 'Турнирлер өткізілді',
      athletes: 'Спортшылар тіркелді',
      matches: 'Жекпе-жектер жүргізілді',
      clubs: 'Клубтар қосылды',
    },
  },

  // Auth
  auth: {
    loginTitle: 'Жүйеге кіру',
    registerTitle: 'Тіркелу',
    email: 'Электрондық пошта',
    password: 'Құпия сөз',
    confirmPassword: 'Құпия сөзді растау',
    fullName: 'Толық аты-жөні',
    loginButton: 'Кіру',
    registerButton: 'Тіркелу',
    noAccount: 'Тіркелгіңіз жоқ па?',
    hasAccount: 'Тіркелгіңіз бар ма?',
    forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
    orContinue: 'немесе жалғастыру',
    selectRole: 'Рөлді таңдаңыз',
  },

  // Dashboard
  dashboard: {
    welcome: 'Қош келдіңіз',
    overview: 'Жалпы шолу',
    recentActivity: 'Соңғы белсенділік',
    quickActions: 'Жылдам әрекеттер',
    totalTournaments: 'Барлық турнирлер',
    activeTournaments: 'Белсенді турнирлер',
    totalAthletes: 'Барлық спортшылар',
    pendingApplications: 'Күтілуде өтінімдер',
    totalMatches: 'Барлық жекпе-жектер',
    activeMatches: 'Белсенді жекпе-жектер',
    todayMatches: 'Бүгінгі жекпе-жектер',
    totalClubs: 'Барлық клубтар',
    upcomingEvents: 'Алдағы іс-шаралар',
    myTournaments: 'Менің турнирлерім',
    myApplications: 'Менің өтінімдерім',
    myResults: 'Менің нәтижелерім',
    myAthletes: 'Менің спортшыларым',
    notifications: 'Хабарламалар',
    performance: 'Көрсеткіштер',
  },

  // Tournament
  tournament: {
    create: 'Турнир құру',
    edit: 'Турнирді өзгерту',
    details: 'Турнир мәліметтері',
    name: 'Турнир атауы',
    date: 'Басталу күні',
    endDate: 'Аяқталу күні',
    location: 'Орын',
    status: 'Мәртебе',
    categories: 'Санаттар',
    participants: 'Қатысушылар',
    maxParticipants: 'Максимум қатысушылар',
    boutDuration: 'Жекпе-жек ұзақтығы',
    boutDurationMin: 'мин',
    description: 'Сипаттама',
    organizer: 'Ұйымдастырушы',
    ageGroups: 'Жас топтары',
    weightCategories: 'Салмақ санаттары',
    save: 'Сақтау',
    cancel: 'Бас тарту',
    delete: 'Жою',
    publish: 'Жариялау',
    viewBracket: 'Турнир торын көру',
    manageApplications: 'Өтінімдерді басқару',
    tatami: 'Татами',
    schedule: 'Кесте',
    results: 'Нәтижелер',
    operations: 'Операциялар',
    noTournaments: 'Турнирлер жоқ',
  },

  // Application (site / club join requests)
  application: {
    submit: 'Өтінім жіберу',
    review: 'Өтінімдерді тексеру',
    approve: 'Мақұлдау',
    reject: 'Қабылдамау',
    athlete: 'Спортшы',
    club: 'Клуб',
    category: 'Санат',
    weight: 'Салмақ',
    submittedAt: 'Жіберілген уақыт',
    coach: 'Жаттықтырушы',
    filterByStatus: 'Мәртебе бойынша сүзу',
    filterByCategory: 'Тип бойынша сүзу',
    all: 'Барлығы',
    noApplications: 'Өтінімдер жоқ',
    bulkApprove: 'Барлығын мақұлдау',
    bulkReject: 'Барлығын қабылдамау',
    // New: site/club join request labels
    siteJoin: 'Сайтқа тіркелу',
    clubJoin: 'Клубқа қосылу',
    teamJoin: 'Команда тіркелу',
    applicantName: 'Өтінім берушінің аты',
    applicantType: 'Өтінім түрі',
    requestDate: 'Өтінім күні',
    contactInfo: 'Байланыс ақпараты',
    phone: 'Телефон',
    notes: 'Ескертпе',
    typeAll: 'Барлық түрлері',
    typeSite: 'Сайтқа тіркелу',
    typeClub: 'Клубқа қосылу',
    typeTeam: 'Команда тіркелу',
  },

  // Bracket
  bracket: {
    title: 'Турнир торы',
    round: 'Раунд',
    quarterfinal: 'Ширек финал',
    semifinal: 'Жартылай финал',
    final: 'Финал',
    winner: 'Жеңімпаз',
    bronze: 'Қола жекпе-жек',
    bye: 'Бос',
    noMatches: 'Жекпе-жектер жоқ',
  },

  // Judge
  judge: {
    matchControl: 'Жекпе-жек басқару',
    timer: 'Таймер',
    start: 'Бастау',
    stop: 'Тоқтату',
    reset: 'Қалпына келтіру',
    hajime: 'ХАДЖИМЕ',
    matte: 'МАТТЭ',
    soremade: 'СОРЭ МАДЭ',
    ippon: 'ИППОН',
    wazaari: 'ВАЗА-АРИ',
    uko: 'УКО',
    shido: 'ШИДО',
    hansoku: 'ХАНСОКУ МАКЭ',
    osaekomi: 'ОСАЭКОМИ',
    toketa: 'ТОКЭТА',
    athlete1: '1-ші спортшы',
    athlete2: '2-ші спортшы',
    white: 'Ақ',
    blue: 'Көк',
    penalties: 'Жазалар',
    score: 'Ұпай',
    currentMatch: 'Ағымдағы жекпе-жек',
    nextMatch: 'Келесі жекпе-жек',
    endMatch: 'Жекпе-жекті аяқтау',
    confirmResult: 'Нәтижені растау',
    queue: 'Кезек',
    noActiveMatch: 'Белсенді жекпе-жек жоқ',
    goldenScore: 'Алтын ұпай',
  },

  // Tables
  table: {
    name: 'Аты-жөні',
    club: 'Клуб',
    category: 'Санат',
    weight: 'Салмақ',
    age: 'Жас',
    rank: 'Разряд',
    region: 'Аймақ',
    wins: 'Жеңістер',
    losses: 'Жеңілістер',
    actions: 'Әрекеттер',
    search: 'Іздеу...',
    noData: 'Деректер жоқ',
    showing: 'Көрсетілуде',
    of: '/',
    view: 'Көру',
    edit: 'Өзгерту',
    delete: 'Жою',
  },

  // Users management
  users: {
    addUser: 'Пайдаланушы қосу',
    editUser: 'Пайдаланушыны өзгерту',
    deleteUser: 'Пайдаланушыны жою',
    blockUser: 'Бұғаттау',
    unblockUser: 'Бұғаттан шығару',
    resetPassword: 'Құпия сөзді қалпына келтіру',
    role: 'Рөл',
    email: 'Электрондық пошта',
    phone: 'Телефон',
    registeredAt: 'Тіркелген күні',
    lastActive: 'Соңғы белсенділік',
    status: 'Мәртебе',
    confirmDelete: 'Бұл пайдаланушыны жоюға сенімдісіз бе?',
    userDetails: 'Пайдаланушы мәліметтері',
    allRoles: 'Барлық рөлдер',
    filterByRole: 'Рөл бойынша сүзу',
  },

  // Clubs management
  clubs: {
    addClub: 'Клуб қосу',
    editClub: 'Клубты өзгерту',
    deleteClub: 'Клубты жою',
    clubName: 'Клуб атауы',
    city: 'Қала',
    region: 'Аймақ',
    coach: 'Бас жаттықтырушы',
    athleteCount: 'Спортшылар саны',
    founded: 'Құрылған жылы',
    phone: 'Телефон',
    address: 'Мекен-жай',
    confirmDelete: 'Бұл клубты жоюға сенімдісіз бе?',
    clubDetails: 'Клуб мәліметтері',
  },

  // Common
  common: {
    save: 'Сақтау',
    cancel: 'Бас тарту',
    delete: 'Жою',
    edit: 'Өзгерту',
    create: 'Құру',
    close: 'Жабу',
    back: 'Артқа',
    next: 'Келесі',
    previous: 'Алдыңғы',
    loading: 'Жүктелуде...',
    error: 'Қате орын алды',
    success: 'Сәтті орындалды',
    confirm: 'Растау',
    yes: 'Иә',
    no: 'Жоқ',
    total: 'Барлығы',
    filter: 'Сүзу',
    export: 'Экспорт',
    import: 'Импорт',
    refresh: 'Жаңарту',
    add: 'Қосу',
  },
};
