module.exports = {
    APPLICATION_APPROVED: 'APPLICATION_APPROVED',
    APPLICATION_REJECTED: 'APPLICATION_REJECTED',
    BRACKET_GENERATED: 'BRACKET_GENERATED',
    MATCH_COMPLETED: 'MATCH_COMPLETED',
    MATCH_OVERRIDE: 'MATCH_OVERRIDE',
    MATCH_ROLLBACK: 'MATCH_ROLLBACK',
    TOURNAMENT_STARTED: 'TOURNAMENT_STARTED',
    TOURNAMENT_PAUSED: 'TOURNAMENT_PAUSED',
    TOURNAMENT_COMPLETED: 'TOURNAMENT_COMPLETED',
  };