name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies (API)
      run: npm install
      working-directory: ./api
      
    - name: Install dependencies (Web)
      run: npm install
      working-directory: ./web

    - name: Lint API
      run: npm run lint
      working-directory: ./api
      
    - name: Build Web
      run: npm run build
      working-directory: ./web
      
    - name: Run Unit Tests (API)
      run: npm run test
      working-directory: ./api
      
  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://localhost:8080
